name: Test Coverage Check
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install

      - name: run  Test Coverage
        run: npm run test -- --coverage

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  